/*
 * Copyright (c) 2018 Victor Rendina
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.victorrendina.dagger2.lifecycle.sample.di.lifecycle

import com.victorrendina.dagger2.lifecycle.DaggerLifecycleDependencyProvider
import com.victorrendina.dagger2.lifecycle.DaggerLifecycleManager
import com.victorrendina.dagger2.lifecycle.sample.di.components.ScopeOneComponent
import com.victorrendina.dagger2.lifecycle.sample.di.components.ScopeOneComponentLifecycleDeps
import javax.inject.Inject

class ScopeOneLifecycleManager(val component: ScopeOneComponent) : DaggerLifecycleManager() {

    @Inject
    lateinit var provider: ScopeOneComponentLifecycleDeps // Generated by DaggerLifecycle

    init {
        component.inject(this)
    }

    override fun getProvider(): DaggerLifecycleDependencyProvider = provider
}